### ISSUE TITLE
Ensretning af afsnit om træer

### ISSUE THREAD

**Issue by StefanMich** [des904e15/report#38]
Vi skal have en konvention for hvad afsnittene skal hedde
Lige nu er der 47 bud, heriblandt:
- Reporting a low power consumption
- Burglar
- Partner vs Consumer
- Information gatherer attacking the consumer

**Comment by StefanMich** [comment]
"Information gatherer attacking the consumer" vandt

**Comment by deaddog** [comment]
Stefan er dåm!
