### ISSUE TITLE
Related work: Off-switch - Ross Anderson

### ISSUE THREAD

**Issue by Thalmann** [des904e15/report#4]

**Comment by Thalmann** [comment]
Todo tilføjet med spørgsmål :)

**Comment by StefanMich** [comment]
Til næste reviewer: kig mine to todos

**Comment by MikaelElkiaer** [comment]
Har reviewet, næste reviewer se: https://github.com/des904e15/report/commit/43adbc33664ec15277cf2f59b1808f1c663289ca.

**Comment by Thalmann** [comment]
Snakket om todos efter morgenmøde og de er blevet fjernet.
