### ISSUE TITLE
Smart meter antagelser

### ISSUE THREAD

**Issue by StefanMich** [des904e15/report#60]
Belæg for vores konceptuelle SM

**Comment by MikaelElkiaer** [comment]
I 3.2.1, referér til Background og TDLM-rapporten.

**Comment by MikaelElkiaer** [comment]
I 3.2.2, under Object > Smart Meter -- ret beskrivelse til så der kun står de ting der er nødvendige for attack trees, og som vi ved er beskrevet i de forskellige lovforslag etc.
