### ISSUE TITLE
Opsummering af træer

### ISSUE THREAD

**Issue by Thalmann** [des904e15/report#68]
En opsummering af sikkerhedstrusler man skal overveje hvis man skal implementere sikkerhed på et SM.

En opsummering a privacy concerns man skal overveje hvis man skal implementere/designe en arkitektur/protokol der højner privacy.

Flere?!

**Comment by MikaelElkiaer** [comment]
Et afsnit i 'Attack Trees': opsummering/gruppering af de problemer fundet.

**Comment by MikaelElkiaer** [comment]
Er nu en del af den overordnede konklusion.

**Comment by MikaelElkiaer** [comment]
![img_20160108_135814](https://cloud.githubusercontent.com/assets/2102306/12198439/1d815374-b610-11e5-9114-7aff95da48d4.jpg)
