### ISSUE TITLE
Undersøg om der er et angreb fra Dist

### ISSUE THREAD

**Issue by StefanMich** [des904e15/report#77]
Hvordan fungerer dist?
Har dist mulighed for at måle på en enkelt consumer eller er de grupperet?

**Comment by MikaelElkiaer** [comment]
Har nu brugt ~30 minutter på den her, har intet kunne finde.
Masser af dokumentation om hvordan netvirksomhederne afregner med leverandør, men utroligt lidt om netvirksomhedernes forhold til slutbrugeren.
