### ISSUE TITLE
Indsæt gennemgående eksempel i DLM

### ISSUE THREAD

**Issue by MikaelElkiaer** [des904e15/report#83]
Brug fx hospitals eksemplet fra phd rapporten.

**Comment by MikaelElkiaer** [comment]
Ikke så gennemgående...

**Comment by Thalmann** [comment]
Synes ikke eksemplet rigtig giver noget :)

**Comment by StefanMich** [comment]
Jeg synes eksemplet gør det lettere at forstå, og det refereres i "Applicability in a smart meter context" afsnittet
