### ISSUE TITLE
Ret Mads stavefejl

### ISSUE THREAD

**Issue by MikaelElkiaer** [des904e15/report#85]
Alle rettelser som ikke har kuglepens-checkmark.

**Comment by StefanMich** [comment]
Ret Mikaels stavefejl

Mads -> Mads'

**Comment by MikaelElkiaer** [comment]
Hah @stufkan ! Det var med fuldt overlæg. Det er jo ikke Mads' stavefejl, altså ikke ham der har lavet dem, det er stavefejl relateret til Mads!
